# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c019d7dc802e85eaf0e22517e58d0e0bb47b916cc02de577ea0e3a1437ca721b0934cddb1e68a427c6b39b512ff39f6339a76c42103684ae6ddc9f3467675416

test:
  secret_key_base: 7944e806d5b312f9d0539c92b119245703c671c07a7414c9ea30a7d6b78b2ed3ed7dfd9ef4eded522f2a57c22a05c94cc7cabf5e382870ee360f498e1db5fbe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
